# Generated by Django 4.2 on 2023-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecords',
            name='general_health',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('poor', 'Poor')], max_length=6, null=True),
        ),
    ]
